### ISSUE TITLE
Anchor Links on Page

### ISSUE THREAD

**Issue by jonathanamartin** [ramiel/router.js#17]
Hey there,

Again great library!  Just had a question about anchor links on a page.  Do you have any recommendations for handling anchor/jump links on a page?  For example, is there a way to change the route delimiter to use something like '#!'?

Any help would be greatly appreciated.

**Comment by ramiel** [comment]
Hi,
the only available option to handle anchor links is for ignore case on anchors. There is no option to change the delimiter. I think you can use the delimiter you want because the route engine check the string after the `#` symbol so, if there is a `!` should be equivalent. Anyway I haven't testd. If you notice an issue just say to me. We could do:

- an option to choose the starting delimiter (PR wellcome)
- or accept any symbol (PR wellcome)

So, I don't have any specific raccomandations but I can say the only well tested situation involves using only `#` as symbol.

**Comment by jonathanamartin** [comment]
Hey sounds good.  I'll take a look at adding an option and doing some testing with that.  Thanks for the info.
