### ISSUE TITLE
Match request based on existence of specific query params

### ISSUE THREAD

**Issue by jonathanamartin** [ramiel/router.js#21]
Hey there.  Great router, so far it's met our needs very well.

I was wondering if there is a way to more easily match a request based on the existence of a query parameter.

I see we can use regular expressions but I just can't seem to get that to work for a specific query param (may be my lack of expertise with regex).

It'd be nice if there was a convenient way to match based on the existence of a query param.  Something like `#/some/:param1/path?**param2=:param2` or `#/**?**param2=:param2`.

Again, you can probably do this using regular expressions, if I haven't been able to figure that one out yet.

Here are some tests I've done:
https://jsfiddle.net/LLp3nqp0/3/

Any help would be greatly appreciated.

**Comment by ramiel** [comment]
Hi, I gave a look to your example code and, apart from your main question, it looks like you have a bit of confusion. For example you have a route like this
```javascript
.addRoute('#/users/:userid**', function(req, next){...}
```
You should not put ** after the `:userid` especially if your route is `#/user/1`. In this case the ** has no utility at all and your route could be simply `#/user/:userid`.
`**` is meant to match anything but just **before** the query parameters, so before the **?**.
And because in this case the same is matched by `:userid`, nothing will be matched by `**`. For example:
```
If the fragment is
#/users/123?p=yes

The matching parts will be:
:userid = 123
** = nothing
query = {p: 'yes'}
```

Then, let's come to your question. 
**Short answer**
There is no way to use query parameters to distinguish between two routes.   
    
**Long answer tl;dr**
I think that if you're trying to use the query parameters as a way to distinguish two different routes there is something wrong. Maybe you could explain better your use case.
What do you have to achieve exactly? Can you write the real problem which let you came up with this problem?

There should be no reason to use the query parameters for this purpose because the same result should be reached using the tools you already have.

By the way a simple answer is that you can write a normal route and then use the query parameters to have different behaviors like in this example
```javascript
router.addRoute('#/users/:userid/details', function(req, next){
    if(req.query.showprofile === 'true'){
        doSomethingWithProfile(req.params.userid);
    }else{
       doSomethingElse(req.params.userid);
   }
});
```

Let me know if this helps.

**Comment by jonathanamartin** [comment]
Hey thanks for the quick reply.  I think the workaround you mentioned should do the trick for us.

**Comment by ramiel** [comment]
Good to know.
By the way I'm still curious about the practical issue which originated the question ;)
